# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
include:
  project: "bmi/opendesk/tooling/gitlab-config"
  ref: "v2.3.0"
  file:
    - "ci/common/lint.yml"
    - "ci/container/container-build-semantic.yml"
    - "ci/container/container-lint.yml"

stages:
  - ".pre"
  - "lint"
  - "build"
  - "scan"
  - "release"
  - ".post"

.common:
  tags: []

...
